apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: fin-crawling
spec:
  type: NodePort
  ports:
  - name: mongo-express
    port: 8081
    nodePort: 30002

  selector:
    app: mongo-express

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: fin-crawling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: fin-db-mongo-express
        image: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "root"
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: "example"
          - name: ME_CONFIG_MONGODB_SERVER
            value: "mongo"


