version: '3.1'
services:
  commander:
    build:
      context: ./commander
      dockerfile: ./Dockerfile
    depends_on:
      - webdriver
  webdriver:
    build:
      context: ./webdriver
      dockerfile: ./Dockerfile
    ports:
      - 4444:4444
    volumes: 
      - /dev/shm:/dev/shm

