version: '3.1'
services:
  commander:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    depends_on:
      - webdriver
    ports:
      - 5000:5000
    volumes:
      - ./downloads:/usr/src/downloads
      - ./app:/usr/src/app
      - ./log:/usr/src/app/log
    networks:
      - database
  webdriver:
    build:
      context: ./webdriver
      dockerfile: ./Dockerfile
    ports:
      - 4444:4444
    volumes: 
      - /dev/shm:/dev/shm
      - ./downloads:/home/seluser/Downloads
    networks:
      - database
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - commander
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - database
networks: 
  database:
    name: mongo-server
    external: true
