version: '3.1'
services:
  commander:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    depends_on:
      - webdriver
    ports:
      - 5000:5000
    volumes:
      - ./downloads:/usr/src/downloads
      - ./fin_crawling:/usr/src/fin_crawling
  webdriver:
    build:
      context: ./webdriver
      dockerfile: ./Dockerfile
    ports:
      - 4444:4444
    volumes: 
      - /dev/shm:/dev/shm
      - ./downloads:/home/seluser/Downloads

