apiVersion: v1
kind: Service
metadata:
  name: fin-carwling-webdriver
  namespace: fin-crawling
spec:
  ports:
  - name: http
    port: 4444
  selector:
    app: fin-carwling-webdriver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-carwling-webdriver
  namespace: fin-crawling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-carwling-webdriver
  template:
    metadata:
      labels:
        app: fin-carwling-webdriver
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: fin-carwling-webdriver
        image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618
        imagePullPolicy: Always
        volumeMounts:
        - name: shm-file
          mountPath: /dev/shm
        - name: download-data
          mountPath: /home/seluser/Downloads
        env:
        - name: SE_NODE_MAX_SESSIONS
          value: "10"
        - name: SE_NODE_OVERRIDE_MAX_SESSIONS
          value: "true"
      volumes:
      - name: shm-file
        hostPath: 
          path: /dev/shm
          type: DirectoryOrCreate
      - name: download-data
        hostPath: 
          path: /Users/iseongjae/Documents/PersonalProjects/fin-web/fin-crawling-server/downloads
          type: DirectoryOrCreate
    


